#!/bin/bash

### only run on Linux ###
OS=$(uname -o)
if [[ ${OS} != "GNU/Linux" ]];
  echo "==> ERROR: Only runs on Linux. Detected OS: ${OS}"
fi

### run as root ###
if [[ ${UID} -ne 0 ]];
  echo "==> ERROR: root-access required to load/unload kernel modules"
  exit 1
fi

# kvm-intel depends on kvm so remove it first"
LOADED_MODULES="kvm-intel kvm"

for MODULE in ${MODULES} ; do
  /sbin/rmmod ${MODULE}
  RC=$?
  if [[ ${RC} -ne 0 ]]; then
    echo "==> Failed unloading: ${MODULE}"
  fi
done

exit ${RC}
