#!/bin/bash

# create venv and .env file for autovenv in current path

# vars
PARAM=$1
CMD="virtualenv venv"
RC=0

# checks

if [[ ${PARAM} != "create" ]]; then
  echo "Usage: $(basename $0) create"
  RC=1
fi

# create venv
if [[ $RC -eq 0 ]]; then
  eval ${CMD}
  RC=$?
fi

# update config files
if [[ $RC -eq 0 ]]; then
  echo "source venv/bin/activate" > .env
else
  echo "==> error creating Python venv. RC: ${RC}"
fi

# update .gitignore
if [[ $RC -eq 0 ]]; then
  echo .env >> .gitignore
  echo venv >> .gitignore
  RC=$?
fi

# print summary and info
if [[ $RC -eq 0 ]]; then
  echo
  echo "* created Python venv:     $(pwd)/venv"
  echo "* created autovenv config: $(pwd)/.env"
  echo "* updated .gitignore"
  echo
  echo "Enter \"cd .\" to activate venv"
  echo "Enter \"deactivate\" to exit"
  echo
fi

cd $(pwd)

exit ${RC}
